
<a href="https://colab.research.google.com/github/kokchun/Machine-learning-AI22/blob/main/Exercises/E01_gradient_descent.ipynb" target="_parent"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a> &nbsp; to see hints and answers.

---
# Gradient descent exercises

---
These are introductory exercises in Machine learning with focus in **gradient descent** .

<p class = "alert alert-info" role="alert"><b>Note</b> all datasets used in this exercise can be found under Data folder of the course Github repo</p>

<p class = "alert alert-info" role="alert"><b>Note</b> that in cases when you start to repeat code, try not to. Create functions to reuse code instead. </p>

<p class = "alert alert-info" role="alert"><b>Remember</b> to use <b>descriptive variable, function, index </b> and <b> column names</b> in order to get readable code </p>

The number of stars (\*), (\*\*), (\*\*\*) denotes the difficulty level of the task

---

## 0. Simulate dataset (*)

Simulate datasets according to these rules:

- set random seed to 42
- (1000,2) samples from $X \sim \mathcal{U}(0,1)$ , i.e. 1000 rows, 2 columns. 
- 1000 samples from $\epsilon \sim \mathcal{N}(0,1)$
- $y = 3x_1 + 5x_2 + 3 + \epsilon$ , where $x_i$ is column $i$ of $X$

Finally add a column of ones for the intercept to $X$.

<details>

<summary>Hint</summary>

Use for simulating X

´´´
np.random.rand(samples, 2)
´´´

to concatenate with ones, use ```np.c_[..., ...]```

</details>

<details>

<summary>Answer</summary>

```
array([[1.        , 0.37454012, 0.95071431],
       [1.        , 0.73199394, 0.59865848],
       [1.        , 0.15601864, 0.15599452],
       [1.        , 0.05808361, 0.86617615],
       [1.        , 0.60111501, 0.70807258]])

```

</details>

---

In [1]:
import numpy as np
np.random.seed(42) # set seed
X = np.random.uniform(size=(1000, 2)) # generate X~U(0, 1)

X[0], X.shape

(array([0.37454012, 0.95071431]), (1000, 2))

In [2]:
np.random.seed(42)
e = np.random.normal(size=(1000, 1)) # epsilon (noise)

e[1],e[0],e[-1], e.size

(array([-0.1382643]), array([0.49671415]), array([0.57258278]), 1000)

In [3]:
np.random.seed(42)

beta = [3, 5, 3]
# y = 3x1 + 5x2 + 3 + noise
y = beta[0] * X[:, 0] + beta[1] * X[:, 1] + beta[2] + e.flatten() # access column by slicing, flatten epsilon to fit

X = np.c_[(np.ones((1000, 1)), X)] # concatenate ones for intercept

In [4]:
np.random.seed(42)
X, X.shape, y.shape

(array([[1.        , 0.37454012, 0.95071431],
        [1.        , 0.73199394, 0.59865848],
        [1.        , 0.15601864, 0.15599452],
        ...,
        [1.        , 0.75137509, 0.65695516],
        [1.        , 0.95661462, 0.06895802],
        [1.        , 0.05705472, 0.28218707]]),
 (1000, 3),
 (1000,))

In [5]:
 y = y.reshape(-1, 1)
 y.shape

(1000, 1)

## 1. Gradient descent - learning rate (*)

Use gradient descent to calculate $\vec{\theta} = (\theta_0, \theta_1, \theta_2)^T$ 

&nbsp; a) Use $\eta = 0.1$ and calculate $\vec{\theta}$ for each fifth epoch from 1 to 500. So the procedure is as follows:
- calculate $\vec{\theta}$ for epochs = 1
- calculate $\vec{\theta}$ for epochs = 6
- ...
- calculate $\vec{\theta}$ for epochs = 496

Plot these $\vec{\theta}$ values against epochs. (*)

&nbsp; b) Do the same as for a) but with learning rate $\eta = 0.01$, 5000 epochs and for each 20th epoch. What do you notice when changing the learning rate? (*)

&nbsp; c) Experiment with larger and smaller $\eta$ and see what happens.

<details>

<summary>Answer</summary>

a) 

<img src="../assets/grad_desc_converg.png" height="200"/>

b) 

<img src="../assets/grad_desc_converg_001.png" height="200"/>

</details>

---

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42)
X_train, X_train.shape

(array([[1.        , 0.41758078, 0.87911831],
        [1.        , 0.2310748 , 0.67189274],
        [1.        , 0.28869374, 0.35567272],
        ...,
        [1.        , 0.14224937, 0.12138494],
        [1.        , 0.37330932, 0.27074467],
        [1.        , 0.60642906, 0.00919705]]),
 (700, 3))

## 2. Stochastic Gradient Descent - learning rate (**)

Repeat task 1 but using stochastic gradient descent instead. Also adjust number of epochs to see if you can find convergence. What kind of conclusions can you draw from your experiments. (**)

---

## 3. Mini Batch Gradient Descent (**)

Now try different sizes of mini-batches and make some exploratory plots to see convergence. Also you can make comparison to the other algorithms by using same $\eta$ and same amount of epochs to see how they differ from each other in terms of convergence. (**)

---

Kokchun Giang

[LinkedIn][linkedIn_kokchun]

[GitHub portfolio][github_portfolio]

[linkedIn_kokchun]: https://www.linkedin.com/in/kokchungiang/
[github_portfolio]: https://github.com/kokchun/Portfolio-Kokchun-Giang

---